name: deploy_to_fabric

on:
  push:
    branches:
      - 'develop'

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        bundle install
        pod install
    - name: Deploy to fabric
      run: |
         bundle exec fastlane ios alpha
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.app
        IOS_CERTIFICATES_GIT_URL: ${{ secrets.IOS_CERTIFICATES_GIT_URL }}

        ITUNESCONNECT_EMAIL: ${{ secrets.ITUNESCONNECT_EMAIL }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}

        MATCH_TEAM_ID: ${{ secrets.MATCH_TEAM_ID }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

        CRASHLYTICS_GROUPS: ${{ secrets.CRASHLYTICS_GROUPS }}
        CRASHLYTICS_API_TOKEN: ${{ secrets.CRASHLYTICS_API_TOKEN }}
        CRASHLYTICS_BUILD_SECRET: ${{ secrets.CRASHLYTICS_BUILD_SECRET }}
